error handling

diff --git a/.github/workflows/create_test.yaml b/.github/workflows/create_test.yaml
--- a/.github/workflows/create_test.yaml
+++ b/.github/workflows/create_test.yaml
@@ -69,5 +69,8 @@ jobs:
             "password": "'"${{ secrets.password }}"'",
             "action": "CREATE_TEST"
           }' | jq -r 'to_entries | map("\(.key)=\(.value|@uri)") | join("&")')
-          echo "$DATA"
-          curl -X POST "${{ secrets.url }}" -H "Content-Type: application/x-www-form-urlencoded" -d "$DATA"
+          RES=$(curl -X POST "${{ secrets.url }}" -H "Content-Type: application/x-www-form-urlencoded" -d "$DATA" --write-out "%{http_code}" --silent --output /dev/null)
+          if [ "$RES" -ne 200 ]; then
+            echo "API request failed with status $RES"
+            exit 1
+          fi
